# Generated by Django 5.1.4 on 2025-02-20 11:29

import cadastro_jogos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(default='', max_length=11, unique=True, validators=[cadastro_jogos.validators.validar_cpf], verbose_name='CPF do usuário')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('perfil', models.CharField(choices=[], max_length=50, verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
