# Generated by Django 5.1.4 on 2025-02-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_jogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('Teste', 'Teste'), ('Codata', 'Codata')], max_length=50, verbose_name='Perfil'),
        ),
    ]
