# Generated by Django 5.1.4 on 2025-02-26 13:33

import cadastro_jogos.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_jogos', '0002_alter_usuario_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioJogos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nome do usuário:')),
                ('cpf', models.CharField(default='', max_length=11, unique=True, validators=[cadastro_jogos.validators.validar_cpf], verbose_name='CPF do servidor:')),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('telefone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefone')),
                ('perfil', models.CharField(choices=[('0', 'Responsável Regional'), ('1', 'Responsável Instituição'), ('2', 'Responsável Técnico'), ('3', 'Responsável Sejel')], max_length=1)),
                ('username', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário Jogos',
                'verbose_name_plural': 'Usuários Jogos',
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
