# Generated by Django 5.1.4 on 2025-02-25 11:09

import cadastro_jogos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_jogos', '0002_alter_usuario_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default='', max_length=14, unique=True, validators=[cadastro_jogos.validators.validar_cpf], verbose_name='CPF do usuário'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('Responsável SEJEL', 'Responsável SEJEL'), ('Responsável Regional', 'Responsável Regional'), ('Responsável Instituição', 'Responsável Instituição'), ('Responsável Técnico', 'Responsável Técnico')], max_length=50, verbose_name='Perfil'),
        ),
    ]
