# Generated by Django 5.1.4 on 2025-03-11 10:06

import cadastro_jogos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_jogos', '0003_usuariojogos_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da Regional')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('tipo_regional', models.CharField(choices=[('escolar', 'Escolar'), ('amador', 'Amador'), ('profissional', 'Profissional')], max_length=20, verbose_name='Tipo de Regional')),
            ],
            options={
                'verbose_name': 'Regional',
                'verbose_name_plural': 'Regionais',
            },
        ),
        migrations.AlterField(
            model_name='usuariojogos',
            name='email',
            field=models.CharField(default='', max_length=150, validators=[cadastro_jogos.validators.validar_email]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuariojogos',
            name='nome',
            field=models.CharField(default='Nome', max_length=120, verbose_name='Nome do usuário:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuariojogos',
            name='telefone',
            field=models.CharField(default='', max_length=12, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
