# Generated by Django 5.1.4 on 2025-03-17 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_jogos', '0004_regional_alter_usuariojogos_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioRegional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('regional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_jogos.regional')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_jogos.usuariojogos')),
            ],
            options={
                'verbose_name': 'Usuário Regional',
                'verbose_name_plural': 'Usuários Regionais',
            },
        ),
    ]
