# Generated by Django 5.1.4 on 2025-03-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_jogos', '0005_usuarioregional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioregional',
            name='data_fim',
            field=models.DateField(default='2023-03-10', verbose_name='Data de Fim'),
            preserve_default=False,
        ),
    ]
