# Generated by Django 5.1.4 on 2025-03-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_jogos', '0006_alter_usuarioregional_data_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioregional',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim'),
        ),
    ]
