# Generated by Django 5.1.4 on 2025-03-25 14:20

import cadastro_jogos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_jogos', '0007_alter_usuarioregional_data_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariojogos',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[cadastro_jogos.validators.validar_email]),
        ),
    ]
