# Generated by Django 5.1.4 on 2025-04-03 12:26

import cadastro_jogos.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_jogos', '0008_alter_usuariojogos_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da Instituição')),
                ('cep', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=120)),
                ('logradouro', models.CharField(max_length=120)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=60, null=True)),
                ('municipio', models.CharField(max_length=60)),
                ('pertence_a_regional', models.BooleanField()),
                ('tipo_regional', models.CharField(blank=True, choices=[('escolar', 'Escolar'), ('amador', 'Amador'), ('profissional', 'Profissional')], max_length=20, null=True, verbose_name='Tipo de Regional')),
                ('rede_ensino', models.CharField(blank=True, choices=[('privada', 'Privada'), ('estadual', 'Estadual'), ('municipal', 'Municipal'), ('federal', 'Federal')], max_length=10, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18, null=True, validators=[cadastro_jogos.validators.validar_cpf_cnpj])),
                ('regional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro_jogos.regional')),
            ],
        ),
    ]
