# Generated by Django 5.1.4 on 2025-04-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_jogos', '0009_instituicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncaoProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da Função')),
                ('conselho', models.CharField(blank=True, max_length=120, null=True, verbose_name='Conselho')),
            ],
            options={
                'verbose_name': 'Função Profissional',
                'verbose_name_plural': 'Funções Profissionais',
            },
        ),
    ]
