# Generated by Django 5.1.4 on 2025-04-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_jogos', '0010_funcaoprofissionais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcaoprofissional',
            name='nome',
            field=models.CharField(max_length=121, verbose_name='Nome da Função'),
        ),
    ]
