# Generated by Django 5.2.7 on 2025-10-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_core', '0002_alter_user_options_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
