# Generated by Django 5.1.4 on 2025-04-22 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('oversized', 'Oversized'), ('long', 'Long'), ('cropped', 'Cropped'), ('regata', 'Regata'), ('normal', 'Normal'), ('baby_look', 'Baby Look'), ('outras', 'Outras')], default='unissex', max_length=20)),
                ('quantidade', models.IntegerField(default=0)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camisa',
                'verbose_name_plural': 'Camisas',
                'ordering': ['tipo', '-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('data', models.DateField(blank=True, null=True)),
                ('quantidade_pessoas', models.IntegerField(blank=True, help_text='Número máximo de vagas disponíveis', null=True)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Valor unitário do evento', max_digits=10, null=True)),
                ('contador_inscricoes', models.IntegerField(default=0, editable=False, verbose_name='Inscrições')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aberto', 'Aberto'), ('encerrado', 'Encerrado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidades', models.IntegerField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Planejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor_planejado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=100)),
                ('cache', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eventos', models.ManyToManyField(blank=True, related_name='artistas', to='danca.evento')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('numero_parcelas', models.IntegerField(default=1)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('valor_parcela', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danca.categoria')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InscricaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danca.evento')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricao_evento_set', to='danca.inscricao')),
            ],
            options={
                'verbose_name': 'Evento da Inscrição',
                'verbose_name_plural': 'Eventos das Inscrições',
                'unique_together': {('inscricao', 'evento')},
            },
        ),
        migrations.AddField(
            model_name='inscricao',
            name='eventos',
            field=models.ManyToManyField(related_name='inscricao_eventos', through='danca.InscricaoEvento', to='danca.evento'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danca.lote'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danca.tipoevento'),
        ),
    ]
