# Generated by Django 5.1.4 on 2025-04-10 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('data', models.DateField(blank=True, null=True)),
                ('quantidade_pessoas', models.IntegerField(blank=True, help_text='Número máximo de vagas disponíveis', null=True)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Valor unitário do evento', max_digits=10, null=True)),
                ('contador_inscricoes', models.IntegerField(default=0, editable=False, verbose_name='Inscrições')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aberto', 'Aberto'), ('encerrado', 'Encerrado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danca.tipoevento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
