# Generated by Django 5.1.4 on 2025-04-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0002_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('unissex', 'Unissex')], default='unissex', max_length=20)),
                ('tamanho', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande'), ('GG', 'Extra Grande'), ('XG', 'Extra Grande'), ('XXG', 'Extra Extra Grande')], max_length=3)),
                ('quantidade', models.IntegerField(default=0)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camisa',
                'verbose_name_plural': 'Camisas',
                'ordering': ['tipo', 'tamanho', '-data_atualizacao'],
            },
        ),
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10),
        ),
    ]
