# Generated by Django 5.1.4 on 2025-04-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0003_camisa_alter_lote_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camisa',
            options={'ordering': ['tipo', '-data_atualizacao'], 'verbose_name': 'Camisa', 'verbose_name_plural': 'Camisas'},
        ),
        migrations.RemoveField(
            model_name='camisa',
            name='tamanho',
        ),
        migrations.AlterField(
            model_name='camisa',
            name='tipo',
            field=models.CharField(choices=[('oversized', 'Oversized'), ('long', 'Long'), ('cropped', 'Cropped'), ('regata', 'Regata'), ('normal', 'Normal'), ('baby_look', 'Baby Look'), ('outras', 'Outras')], default='unissex', max_length=20),
        ),
    ]
