# Generated by Django 5.1.4 on 2025-04-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0004_alter_camisa_options_remove_camisa_tamanho_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor_planejado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
