# Generated by Django 5.1.4 on 2025-04-10 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0006_artista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artistas', to='danca.evento'),
        ),
    ]
