# Generated by Django 5.1.4 on 2025-04-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0007_alter_artista_evento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artista',
            options={'verbose_name': 'Artista', 'verbose_name_plural': 'Artistas'},
        ),
        migrations.RemoveField(
            model_name='artista',
            name='evento',
        ),
        migrations.AddField(
            model_name='artista',
            name='eventos',
            field=models.ManyToManyField(blank=True, related_name='artistas', to='danca.evento'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='cache',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
