# Generated by Django 5.1.4 on 2025-04-15 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0008_alter_artista_options_remove_artista_evento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('numero_parcelas', models.IntegerField(default=1)),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danca.categoria')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danca.lote')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='InscricaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danca.evento')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='danca.inscricao')),
            ],
            options={
                'verbose_name': 'Evento da Inscrição',
                'verbose_name_plural': 'Eventos das Inscrições',
                'unique_together': {('inscricao', 'evento')},
            },
        ),
    ]
