# Generated by Django 5.1.4 on 2025-04-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0009_inscricao_inscricaoevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
