# Generated by Django 5.1.4 on 2025-04-15 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0010_alter_inscricao_cpf_alter_inscricao_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='eventos',
            field=models.ManyToManyField(related_name='inscricao_eventos', to='danca.evento'),
        ),
        migrations.AlterField(
            model_name='inscricaoevento',
            name='inscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricao_evento_set', to='danca.inscricao'),
        ),
    ]
