# Generated by Django 5.1.4 on 2025-06-30 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0011_pagamento_numero_parcela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='funcao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='danca.categoria'),
            preserve_default=False,
        ),
    ]
