# Generated by Django 5.1.4 on 2025-04-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0011_inscricao_eventos_alter_inscricaoevento_inscricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricao',
            options={'ordering': ['-id'], 'verbose_name': 'Inscrição', 'verbose_name_plural': 'Inscrições'},
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='data_criacao',
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
