# Generated by Django 5.1.4 on 2025-04-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0012_alter_inscricao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='valor_parcela',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
