# Generated by Django 5.1.4 on 2025-08-01 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('danca', '0012_alter_profissional_funcao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camisa',
            options={'ordering': ['tipo', '-data_cadastro'], 'verbose_name': 'Camisa', 'verbose_name_plural': 'Camisas'},
        ),
        migrations.RenameField(
            model_name='camisa',
            old_name='data_criacao',
            new_name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='camisa',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='camisa',
            name='valor_unitario',
        ),
        migrations.AddField(
            model_name='camisa',
            name='valor_compra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Custo para a organização', max_digits=10),
        ),
        migrations.AddField(
            model_name='camisa',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Preço para participantes', max_digits=10),
        ),
        migrations.CreateModel(
            name='PedidoCamisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('cor', models.CharField(choices=[('branco', 'Branco'), ('preto', 'Preto'), ('azul', 'Azul'), ('vermelho', 'Vermelho'), ('verde', 'Verde'), ('amarelo', 'Amarelo'), ('cinza', 'Cinza')], max_length=20)),
                ('tamanho', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande'), ('GG', 'Extra Grande'), ('XG', 'Extra Grande'), ('XXG', 'Extra Extra Grande')], max_length=5)),
                ('valor_venda', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente (não pago)'), ('pago', 'Pago'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('camisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danca.camisa')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Pedido de Camisa',
                'verbose_name_plural': 'Pedidos de Camisas',
            },
        ),
    ]
