# Generated by Django 5.1.4 on 2025-08-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0013_alter_camisa_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='pedidocamisa',
            name='cor',
            field=models.CharField(choices=[('branco', 'Branco'), ('verde', 'Verde'), ('laranja', 'Laranja'), ('rosa', 'Rosa'), ('roxo', 'Roxo'), ('marrom', 'Marrom'), ('preto', 'Preto'), ('azul', 'Azul'), ('vermelho', 'Vermelho'), ('amarelo', 'Amarelo'), ('cinza', 'Cinza')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidocamisa',
            name='tamanho',
            field=models.CharField(choices=[('PP', 'Pequeno(PP)'), ('P', 'Pequeno(P)'), ('M', 'Médio(M)'), ('G', 'Grande(G)'), ('GG', 'Extra Grande(GG)'), ('XG', 'Extra Grande(XG)'), ('XXG', 'Extra Extra Grande(XXG)')], max_length=5),
        ),
    ]
