# Generated by Django 5.1.4 on 2025-08-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0014_clienteexterno_alter_pedidocamisa_cor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClienteExterno',
        ),
        migrations.RemoveField(
            model_name='pedidocamisa',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='pedidocamisa',
            name='object_id',
        ),
        migrations.AddField(
            model_name='pedidocamisa',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedidocamisa',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedidocamisa',
            name='tipo_cliente',
            field=models.CharField(blank=True, choices=[('inscricao', 'Congressista'), ('profissional', 'Profissional'), ('externo', 'Cliente Externo')], max_length=20, null=True),
        ),
    ]
