# Generated by Django 5.1.4 on 2025-08-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0015_delete_clienteexterno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocamisa',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
