# Generated by Django 5.2.7 on 2025-10-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0016_pedidocamisa_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profissionais/'),
        ),
        migrations.AlterField(
            model_name='pedidocamisa',
            name='tipo_cliente',
            field=models.CharField(blank=True, choices=[('inscricao', 'Congressista'), ('profissional', 'Profissional'), ('externo', 'Cliente Externo'), ('equipe', 'Equipe'), ('colaborador', 'Colaborador')], max_length=20, null=True),
        ),
    ]
