# Generated by Django 5.2.7 on 2025-10-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0017_profissional_foto_alter_pedidocamisa_tipo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='inscricoes/'),
        ),
    ]
