# Generated by Django 5.2.7 on 2025-10-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0018_inscricao_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='bandeira_cartao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='gateway_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='nome_cartao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='ultimos_digitos',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
