# Generated by Django 5.2.7 on 2025-10-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danca', '0019_pagamento_bandeira_cartao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamento',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AddField(
            model_name='planejamento',
            name='status_gasto',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluído')], default='pendente', max_length=20, verbose_name='Status do Gasto'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='tipo_modelo',
            field=models.CharField(choices=[('planejamento', 'Planejamento'), ('inscricao', 'Inscrição'), ('pedido', 'Pedido de Camisa')], max_length=20),
        ),
    ]
